POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlRvbWltdW5pbGwxNyIsImlkIjoiNjU3ZjExZDNlNDQ3MmQzN2YxYzE3YmM3IiwiaWF0IjoxNzAyODQyMzYyfQ.QCRbbINxtKLoJpSj4XufDk_QR158U-xndgmTafygGNo

{
  "title": "Test driven development",
  "author": "Juan Perez",
  "url": "https://aboutTDD.com/",
  "likes": 0
}