PUT http://localhost:3003/api/blogs/657f46ff9c6eade2e10a4893
Content-Type: application/json

{
  "title": "Cocina blog",
  "author": "Sofia Perez",
  "url": "sofiacocina.com/blogs/receta",
  "likes": 59,
  "user": "657f11d3e4472d37f1c17bc7"
}